dist: trusty
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - bc
      - google-chrome-stable
      - wget

matrix:
  include:
    - language: python
      python:
        - "2.7"
      before_install:
        # Install bazel.
        - wget https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel_0.21.0-linux-x86_64.deb
        - echo cdc225dd1c1eb52ac7f4b0bebb40d2c6d6d8bc0f273718b26281077cd70a0403 bazel_0.21.0-linux-x86_64.deb | sha256sum -c
        - sudo dpkg -i bazel_0.21.0-linux-x86_64.deb
        - rm bazel_0.21.0-linux-x86_64.deb
      script:
        - ./backend_tests.sh $GROUP $TOTAL_GROUPS
      env:
        - GROUP=0
        - GROUP=1
        - GROUP=2
        - GROUP=3
        - GROUP=4
    - language: node_js
      node_js:
        - "8.11.0"
      before_install:
        # Enabled Google Chrome Headless.
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      before_script:
        # This is due to https://github.com/travis-ci/travis-ci/issues/9024
        - "sudo chown root /opt/google/chrome/chrome-sandbox"
        - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
      script:
        - ./angular_tests.sh

env:
  global:
    - TOTAL_GROUPS=5
